### ISSUE TITLE
🚨・Unhandled promise rejection

### ISSUE THREAD

**Issue by 0xj0n1** [CorwinDev/Discord-Bot#102]
`🚨・Unhandled promise rejection
Error
Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
Stack error
Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/runner/Critical/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250:15)
    at async Client.login (/home/runner/Critical/node_modules/discord.js/src/client/Client.js:226:7)`

**Comment by CorwinDev** [comment]
No need to post this 2 times, and we handle errors like this in our discord https://discord.gg/corwindev-1016942011024158782
