### ISSUE TITLE
A websocket connection encountered an error

### ISSUE THREAD

**Issue by caxtry** [CorwinDev/Discord-Bot#115]
Error
TypeError: Cannot read properties of null (reading 'broadcastEval')
Stack error
TypeError: Cannot read properties of null (reading 'broadcastEval')
    at module.exports (/home/runner/DiscordBot/src/events/client/guildDelete.js:49:18)
    at Client.emit (node:events:527:28)
    at GuildDeleteAction.handle (/home/runner/DiscordBot/node_modules/discord.js/src/client/actions/GuildDelete.js:39:14)
    at Object.module.exports [as GUILD_DELETE] (/home/runner/DiscordBot/node_modules/discord.js/src/client/websocket/handlers/GUILD_DELETE.js:4:30)
    at WebSocketManager.handlePacket (/home/runner/DiscordBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/home/runner/DiscordBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (/home/runner/DiscordBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:328:10)
    at callListener (/home/runner/DiscordBot/node_modules/ws/lib/event-target.js:290:14)
    at... view console for details

**Comment by Ruben-Schadron** [comment]
Try it again when you replaced the file with the latest version
