### ISSUE TITLE
error

### ISSUE THREAD

**Issue by daguesswho** [CorwinDev/Discord-Bot#127]
got this error while trying to run the code 

All rights reserved

System >> Version 10.0.0 loaded

System >> Starting Shard #1 ...

node:internal/modules/cjs/loader:1361
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/Users/tysonfabrw/Documents/Discord-Bot-10.0.0/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 102. This version of Node.js requires
NODE_MODULE_VERSION 111. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1361:18)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/Users/tysonfabrw/Documents/Discord-Bot-10.0.0/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v19.6.1
/Users/tysonfabrw/Documents/Discord-Bot-10.0.0/node_modules/discord.js/src/sharding/Shard.js:162
        reject(new DiscordjsError(ErrorCodes.ShardingReadyDied, this.id));
               ^

Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (/Users/tysonfabrw/Documents/Discord-Bot-10.0.0/node_modules/discord.js/src/sharding/Shard.js:162:16)
    at Object.onceWrapper (node:events:627:26)
    at Shard.emit (node:events:524:35)
    at Shard._handleExit (/Users/tysonfabrw/Documents/Discord-Bot-10.0.0/node_modules/discord.js/src/sharding/Shard.js:412:10)
    at ChildProcess.emit (node:events:512:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12) {
  code: 'ShardingReadyDied'
}

Node.js v19.6.1
tysonfabrw@Tysons-MacBook-Pro Discord-Bot-10.0.0 % node:internal/modules/cjs/loader:1361
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/Users/tysonfabrw/Documents/Discord-Bot-10.0.0/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 102. This version of Node.js requires
NODE_MODULE_VERSION 111. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1361:18)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/Users/tysonfabrw/Documents/Discord-Bot-10.0.0/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v19.6.1

**Comment by CorwinDev** [comment]
Run what it says: npm rebuild
Please refer to our discord where we bring support for setting up the bot.
