### ISSUE TITLE
discord.js error

### ISSUE THREAD

**Issue by fethlex** [CorwinDev/Discord-Bot#136]
i have this error pls help

/home/runner/Discord-Bot-v14/node_modules/discord.js/src/client/actions/InteractionCreate.js:50
        if (channel && !channel.isTextBased()) return;
                                ^

TypeError: channel.isTextBased is not a function
    at InteractionCreateAction.handle (/home/runner/Discord-Bot-v14/node_modules/discord.js/src/client/actions/InteractionCreate.js:50:33)
    at Object.module.exports [as INTERACTION_CREATE] (/home/runner/Discord-Bot-v14/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/runner/Discord-Bot-v14/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/home/runner/Discord-Bot-v14/node_modules/discord.js/src/client/websocket/WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (/home/runner/Discord-Bot-v14/node_modules/discord.js/src/client/websocket/WebSocketShard.js:328:10)
    at callListener (/home/runner/Discord-Bot-v14/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/runner/Discord-Bot-v14/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (/home/runner/Discord-Bot-v14/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:527:28)

**Comment by SeaLeopard35302** [comment]
did you fix the error

**Comment by NyxnLyx** [comment]
I managed to fix the error from here [#9295](https://github.com/discordjs/discord.js/issues/9295)
