### ISSUE TITLE
Error with mongoose

### ISSUE THREAD

**Issue by MackenzieAU** [CorwinDev/Discord-Bot#141]
ERROR:
Unhandled promise rejection: MongooseError: Operation `developers.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/home/runner/TastyShack-bot/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:158:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

Also wanted to go on the discord server but the invite is invalid..

**Comment by MackenzieAU** [comment]
Or 
🚨・Unhandled promise rejection
Error
MongooseError: Operation `developers.findOne()` buffering timed out after 10000ms
Stack error
MongooseError: Operation `developers.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/home/runner/TastyShack-bot/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:158:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

**Comment by CorwinDev** [comment]
Invalid: issue because of wrong configuration
