### ISSUE TITLE
Slash command error

### ISSUE THREAD

**Issue by FlexKleks** [CorwinDev/Discord-Bot#160]
Hey,

I actually have 2 errors. The first error occurs when starting the bot and commands do not work either. 

NPM version 8.5.2
Node version 17.7.1
Windows Server 2019

```
DiscordAPIError[10002]: Unknown Application
    at handleErrors (C:\Users\Administrator\Desktop\Disfcord-Bot\WOOF-Central\Test-Bot\node_modules\@discordjs\rest\dist\index.js:640:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.runRequest (C:\Users\Administrator\Desktop\Disfcord-Bot\WOOF-Central\Test-Bot\node_modules\@discordjs\rest\dist\index.js:1021:23)
    at async SequentialHandler.queueRequest (C:\Users\Administrator\Desktop\Disfcord-Bot\WOOF-Central\Test-Bot\node_modules\@discordjs\rest\dist\index.js:862:14)
    at async REST.request (C:\Users\Administrator\Desktop\Disfcord-Bot\WOOF-Central\Test-Bot\node_modules\@discordjs\rest\dist\index.js:1387:22)
    at async C:\Users\Administrator\Desktop\Disfcord-Bot\WOOF-Central\Test-Bot\src\handlers\loaders\commands.js:42:13 {
  requestBody: {
    files: undefined,
    json: [
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [SlashCommandBuilder],
      [ContextMenuCommandBuilder],
      [ContextMenuCommandBuilder],
      [ContextMenuCommandBuilder],
      [ContextMenuCommandBuilder],
      [ContextMenuCommandBuilder]
    ]
  },
  rawError: { message: 'Unknown Application', code: 10002 },
  code: 10002,
  status: 404,
  method: 'PUT',
  url: 'https://discord.com/api/v9/applications/840692647978991657/commands'
}
```

Two error:
![image](https://user-images.githubusercontent.com/73436303/236699183-2b841e78-25f8-4b0a-95c9-9984bc156735.png)

**Comment by SSTROXX** [comment]
Same error, How did you fix it @FlexKleks

**Comment by titanoset** [comment]
Try write npm i ffmpeg-static and check
