### ISSUE TITLE
Error please help

### ISSUE THREAD

**Issue by SensiblePoet256** [CorwinDev/Discord-Bot#162]
npm run start

> discordbot@10.0.0 start
> node . --trace-warnings

Database >> MongoDB is connecting...

Bot >> Started on 1 servers!
System >> Lavalink connected!
DiscordAPIError[10062]: Unknown interaction
    at SequentialHandler.runRequest (/home/runner/Discord-Bot-V14-no-shards/node_modules/@discordjs/rest/dist/index.js:667:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/home/runner/Discord-Bot-V14-no-shards/node_modules/@discordjs/rest/dist/index.js:464:14)
    at async REST.request (/home/runner/Discord-Bot-V14-no-shards/node_modules/@discordjs/rest/dist/index.js:910:22)
    at async ChatInputCommandInteraction.deferReply (/home/runner/Discord-Bot-V14-no-shards/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:69:5)
    at async Object.run (/home/runner/Discord-Bot-V14-no-shards/src/interactions/Command/help.js:19:9) {
  requestBody: { files: undefined, json: { type: 5, data: [Object] } },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1104916598835380304/aW50ZXJhY3Rpb246MTEwNDkxNjU5ODgzNTM4MDMwNDo3QTVUOFJjOGpOZERrMFhIc0g4bWNzWnNKdEpNT3RLZlQ2Qkg0NmgwY1hGQWpsdUlwMVZUUjBoZks0eVNtNzRwSUJVOHhwaEl0YXpQMGFScnU2QVNrUzhuMW4wWGpkVGxpTkNRZG54WUdIekgwc3RRSmtsd1ljYXhocEdldVc0Sg/callback'
}
System >> Lavalink connected!

**Comment by Frannwash** [comment]
It's the same error that I have

**Comment by MinexGamerz** [comment]
Same bro 😂
