### ISSUE TITLE
When we write a command to the Discord bot via DM, it gives an error.

### ISSUE THREAD

**Issue by MRsuffixx** [CorwinDev/Discord-Bot#200]
When we write a command to the Discord bot via DM, it gives an error. For example, when we type "/help" it gives this error.
"TypeError: Cannot read properties of null (reading 'id')
     at client.embed (/home/container/src/handlers/components/embed.js:196:78)
     at Object.run (/home/container/src/interactions/Command/help.js:53:23)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Unhandled promise rejection: TypeError: Cannot read properties of null (reading 'name')
     at module.exports (/home/container/src/events/client/errorCreate.js:19:60)
     at Client.emit (node:events:513:28)
     at /home/container/src/events/client/interactionCreate.js:72:28
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"

**Comment by Felitendo** [comment]
@MRsuffixx did you manage to fix that issue?
