### ISSUE TITLE
FFmpeg/avconv not found!

### ISSUE THREAD

**Issue by kordnddn** [CorwinDev/Discord-Bot#212]
Error: FFmpeg/avconv not found!
    at Function.getInfo (/home/runner/teswt/node_modules/prism-media/src/core/FFmpeg.js:143:11)
    at Function.create (/home/runner/teswt/node_modules/prism-media/src/core/FFmpeg.js:156:38)
    at new FFmpeg (/home/runner/teswt/node_modules/prism-media/src/core/FFmpeg.js:45:27)
    at Object.transformer (/home/runner/teswt/node_modules/@discordjs/voice/dist/index.js:1699:27)
    at /home/runner/teswt/node_modules/@discordjs/voice/dist/index.js:1855:58
    at Array.map (<anonymous>)
    at Object.createAudioResource (/home/runner/teswt/node_modules/@discordjs/voice/dist/index.js:1855:39)
    at Client.client.startStream (/home/runner/teswt/src/handlers/audio/radio.js:15:32)
    at Client.<anonymous> (/home/runner/teswt/src/handlers/audio/radio.js:77:16)
    at Client.emit (node:events:539:35)

**Comment by TemelReyizz** [comment]
U should install on windows and upload for host ...

sob., 4 lis 2023, 15:33 użytkownik despisecrime ***@***.***>
napisał:
