### ISSUE TITLE
Start problem

### ISSUE THREAD

**Issue by aaDrr7** [CorwinDev/Discord-Bot#223]
Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (/home/container/node_modules/discord.js/src/sharding/Shard.js:178:16)
    at Object.onceWrapper (node:events:629:26)
    at Shard.emit (node:events:526:35)
    at Shard._handleExit (/home/container/node_modules/discord.js/src/sharding/Shard.js:439:10)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

**Comment by gokhansarapevi** [comment]
This was not happening before but now I have the same issue

**Comment by zumberr** [comment]
there is up another error ?
