### ISSUE TITLE
Atlest fix it 

### ISSUE THREAD

**Issue by blucifer1337** [CorwinDev/Discord-Bot#234]
・Unhandled promise rejection
Error
1	Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready.
Copy
Stack error
1	Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready.
2	    at Shard.onDeath (/home/runner/ALL-IN-ONE-Bot-v4/node_modules/discord.js/src/sharding/Shard.js:162:16)
3	    at Object.onceWrapper (node:events:642:26)
4	    at Shard.emit (node:events:539:35)
5	    at Shard._handleExit (/home/runner/ALL-IN-ONE-Bot-v4/node_modules/discord.js/src/sharding/Shard.js:412:10)
6	    at ChildProcess.emit (node:events:527:28)
7	    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

**Comment by KangleJangle** [comment]
Same problem here, everything else is correct on my end just dies and tries relaunching endlessly.

**Comment by vxry3** [comment]
same

**Comment by Newton19855** [comment]
same with me lol

**Comment by Felitendo** [comment]
Delete the package-lock.json and the .npm & node_modules folder. Then do `npm i`

**Comment by vxry3** [comment]
> Delete the package-lock.json and the .npm & node_modules folder. Then do `npm i`

what he said it worked

**Comment by KangleJangle** [comment]
I meant to comment a while back, I fixed this as well. Turns out when you first make a login for the MongoDB thing for some reason the password you set doesn't actually work. If you go in and reset the password to something else it works fine, no clue why that is but it worked for me.
