### ISSUE TITLE
help please i have no clue how to fix this

### ISSUE THREAD

**Issue by KaiKingStreams** [CorwinDev/Discord-Bot#239]
node:internal/url:814
    const href = bindingUrl.parse(input, base, raiseException);
                            ^

TypeError: Invalid URL
    at new URL (node:internal/url:814:29)
    at parseURL (C:\Users\seank\Documents\GitHub\ShaDragonBot\node_modules\undici\lib\core\util.js:49:11)
    at Object.parseOrigin (C:\Users\seank\Documents\GitHub\ShaDragonBot\node_modules\undici\lib\core\util.js:115:9)
    at new Pool (C:\Users\seank\Documents\GitHub\ShaDragonBot\node_modules\undici\lib\pool.js:70:23)
    at new Node (C:\Users\seank\Documents\GitHub\ShaDragonBot\node_modules\erela.js\dist\structures\Node.js:91:21)
    at new Manager (C:\Users\seank\Documents\GitHub\ShaDragonBot\node_modules\erela.js\dist\structures\Manager.js:108:17)
    at Object.<anonymous> (C:\Users\seank\Documents\GitHub\ShaDragonBot\src\bot.js:57:21)
    at Module._compile (node:internal/modules/cjs/loader:1434:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
    at Module.load (node:internal/modules/cjs/loader:1249:32) {
  code: 'ERR_INVALID_URL',
  input: 'http://node2.catfein.com:40046:40046'
}

Node.js v22.2.0
C:\Users\seank\Documents\GitHub\ShaDragonBot\node_modules\discord.js\src\sharding\Shard.js:178
        reject(new DiscordjsError(ErrorCodes.ShardingReadyDied, this.id));
               ^

Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (C:\Users\seank\Documents\GitHub\ShaDragonBot\node_modules\discord.js\src\sharding\Shard.js:178:16)
    at Object.onceWrapper (node:events:635:26)
    at Shard.emit (node:events:532:35)
    at Shard._handleExit (C:\Users\seank\Documents\GitHub\ShaDragonBot\node_modules\discord.js\src\sharding\Shard.js:439:10)
    at ChildProcess.emit (node:events:520:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  code: 'ShardingReadyDied'
}

Node.js v22.2.0

**Comment by Felitendo** [comment]
Just do 'npm rebuild'

**Comment by KaiKingStreams** [comment]
Did that but now i get this error

node:internal/modules/cjs/loader:602
      throw e;
      ^

Error: Cannot find module 'D:\GitHub\ShaDragonBot\node_modules\@discordjs\util\dist\index.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1223:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1211:15)
    at resolveExports (node:internal/modules/cjs/loader:595:14)
    at Module._findPath (node:internal/modules/cjs/loader:685:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1172:27)
    at Module._load (node:internal/modules/cjs/loader:1012:27)
    at Module.require (node:internal/modules/cjs/loader:1271:19)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (D:\GitHub\ShaDragonBot\node_modules\discord.js\src\index.js:3:29)
    at Module._compile (node:internal/modules/cjs/loader:1434:14) {
  code: 'MODULE_NOT_FOUND',
  path: 'D:\\GitHub\\ShaDragonBot\\node_modules\\@discordjs\\util\\package.json'
}

Node.js v22.2.0

**Comment by Felitendo** [comment]
> Did that but now i get this error
> 
> node:internal/modules/cjs/loader:602 throw e; ^
> 
> Error: Cannot find module 'D:\GitHub\ShaDragonBot\node_modules@discordjs\util\dist\index.js' at createEsmNotFoundErr (node:internal/modules/cjs/loader:1223:15) at finalizeEsmResolution (node:internal/modules/cjs/loader:1211:15) at resolveExports (node:internal/modules/cjs/loader:595:14) at Module._findPath (node:internal/modules/cjs/loader:685:31) at Module._resolveFilename (node:internal/modules/cjs/loader:1172:27) at Module._load (node:internal/modules/cjs/loader:1012:27) at Module.require (node:internal/modules/cjs/loader:1271:19) at require (node:internal/modules/helpers:123:16) at Object. (D:\GitHub\ShaDragonBot\node_modules\discord.js\src\index.js:3:29) at Module._compile (node:internal/modules/cjs/loader:1434:14) { code: 'MODULE_NOT_FOUND', path: 'D:\GitHub\ShaDragonBot\node_modules\@discordjs\util\package.json' }
> 
> Node.js v22.2.0

npm i discord.js
