### ISSUE TITLE
Mongodb connection error

### ISSUE THREAD

**Issue by Ezeril** [CorwinDev/Discord-Bot#248]
[ERROR] >> MongoDB >> Failed to connect to MongoDB! >> Error: MongoServerError: bad auth : Authentication failed.
Exiting...
Unhandled promise rejection: Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (/home/container/node_modules/discord.js/src/sharding/Shard.js:185:16)
    at Object.onceWrapper (node:events:632:26)
    at Shard.emit (node:events:529:35)
    at Shard._handleExit (/home/container/node_modules/discord.js/src/sharding/Shard.js:446:10)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12) {
  code: 'ShardingReadyDied'
} 

Still the same errors, I've changed the password of the user the bot uses to connect, deleted the npm, package-lock.json and node_modules files, installed the latest version of mongoose, so I don't understand.

**Comment by gamer167** [comment]
I am thinking it might be an issue with mongoDB

**Comment by gamer167** [comment]
Is it the username supplied by you?
