### ISSUE TITLE
Shard is death

### ISSUE THREAD

**Issue by Hyadawild** [CorwinDev/Discord-Bot#49]
System >> Version 10.0.0 loaded

System >> Starting Shard #1 ...

node:internal/modules/cjs/loader:1189
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libuuid.so.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/Discord-Bot/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
/home/runner/Discord-Bot/node_modules/discord.js/src/sharding/Shard.js:162
        reject(new DiscordjsError(ErrorCodes.ShardingReadyDied, this.id));
               ^

Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (/home/runner/Discord-Bot/node_modules/discord.js/src/sharding/Shard.js:162:16)
    at Object.onceWrapper (node:events:642:26)
    at Shard.emit (node:events:539:35)
    at Shard._handleExit (/home/runner/Discord-Bot/node_modules/discord.js/src/sharding/Shard.js:412:10)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  code: 'ShardingReadyDied'
}

**Comment by CorwinDev** [comment]
Hi, try running `npm i` again.


###### [Join our discord for faster support ;) ](https://discord.gg/qHXxpQKC2H)
