### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by hikaoffical1** [CorwinDev/Discord-Bot#52]
i start bot and this error [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Response>".] {
  code: 'ERR_UNHANDLED_REJECTION'

**Comment by CorwinDev** [comment]
If running on replit: `kill 1` then start the bot again

**Comment by hikaoffical1** [comment]
Thanks

**Comment by hikaoffical1** [comment]
Another problems

Unhandled promise rejection: Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/runner/Discord-Bot-1/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250:15)
    at async Client.login (/home/runner/Discord-Bot-1/node_modules/discord.js/src/client/Client.js:226:7) {
  code: 'DisallowedIntents'
}
/home/runner/Discord-Bot-1/node_modules/discord.js/src/sharding/Shard.js:167
        reject(new DiscordjsError(ErrorCodes.ShardingReadyTimeout, this.id));
               ^

Error [ShardingReadyTimeout]: Shard 0's Client took too long to become ready.
    at Timeout.onTimeout (/home/runner/Discord-Bot-1/node_modules/discord.js/src/sharding/Shard.js:167:16)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'ShardingReadyTimeout'

**Comment by CorwinDev** [comment]
Please join our discord, there is also a advanced tutorial on how to set this up. This isn't a issue...

##### [Join our discord for fastest support](https://discord.gg/qHXxpQKC2H)

**Comment by 0xj0n1** [comment]
I have the same problem

**Comment by 0xj0n1** [comment]
```
🚨・Unhandled promise rejection
Error
Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
Stack error
Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/runner/Critical/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250:15)
    at async Client.login (/home/runner/Critical/node_modules/discord.js/src/client/Client.js:226:7)
```

**Comment by CorwinDev** [comment]
No need to post this 2 times, and we handle errors like this in our discord https://discord.gg/corwindev-1016942011024158782
