### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hikaoffical1** [CorwinDev/Discord-Bot#53]
Unhandled promise rejection: Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/runner/Discord-Bot-3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250:15)
    at async Client.login (/home/runner/Discord-Bot-3/node_modules/discord.js/src/client/Client.js:226:7) {
  code: 'DisallowedIntents'

**Comment by CorwinDev** [comment]
May i again redirect you to the discord?
