### ISSUE TITLE
I have a problem with the bot

### ISSUE THREAD

**Issue by Sandro642** [CorwinDev/Discord-Bot#59]
Hello sorry for incovenience, i have a problem with your bot 

Unhandled promise rejection: Response {
  [Symbol(realm)]: null,
  [Symbol(state)]: {
    aborted: false,
    rangeRequested: false,
    timingAllowPassed: true,
    requestIncludesCredentials: true,
    type: 'default',
    status: 429,
    timingInfo: {
      startTime: 1304.4092040006071,
      redirectStartTime: 0,
      redirectEndTime: 0,
      postRedirectStartTime: 1304.4092040006071,
      finalServiceWorkerStartTime: 0,
      finalNetworkResponseStartTime: 0,
      finalNetworkRequestStartTime: 0,
      endTime: 0,
      encodedBodySize: 435,
      decodedBodySize: 435,
      finalConnectionTimingInfo: null
    },
    cacheState: '',
    statusText: 'Too Many Requests',
    headersList: HeadersList {
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    urlList: [ [URL] ],
    body: { stream: undefined }
  },
  [Symbol(headers)]: HeadersList {
    [Symbol(headers map)]: Map(17) {
      'date' => [Object],
      'content-type' => [Object],
      'transfer-encoding' => [Object],
      'connection' => [Object],
      'retry-after' => [Object],
      'x-frame-options' => [Object],
      'referrer-policy' => [Object],
      'cache-control' => [Object],
      'expires' => [Object],
      'report-to' => [Object],
      'nel' => [Object],
      'vary' => [Object],
      'strict-transport-security' => [Object],
      'x-content-type-options' => [Object],
      'server' => [Object],
      'cf-ray' => [Object],
      'alt-svc' => [Object]
    },
    [Symbol(headers map sorted)]: null
  }
}

**Comment by CorwinDev** [comment]
It seems like your bot is doing to many request, if you're running on Replit try this in shell: `kill 1`

##### [Join our discord for fastest support](https://discord.gg/qHXxpQKC2H)

**Comment by Sandro642** [comment]
New error i'm execute kill 1 but now 

Error: libuuid.so.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/Discord-Bot/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
Unhandled promise rejection: Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (/home/runner/Discord-Bot/node_modules/discord.js/src/sharding/Shard.js:162:16)
    at Object.onceWrapper (node:events:642:26)
    at Shard.emit (node:events:539:35)
    at Shard._handleExit (/home/runner/Discord-Bot/node_modules/discord.js/src/sharding/Shard.js:412:10)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  code: 'ShardingReadyDied'
}
Database >> MongoDB is connecting...
node:internal/modules/cjs/loader:1189
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libuuid.so.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/Discord-Bot/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
Unhandled promise rejection: Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (/home/runner/Discord-Bot/node_modules/discord.js/src/sharding/Shard.js:162:16)
    at Object.onceWrapper (node:events:642:26)
    at Shard.emit (node:events:539:35)
    at Shard._handleExit (/home/runner/Discord-Bot/node_modules/discord.js/src/sharding/Shard.js:412:10)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  code: 'ShardingReadyDied'
}
Database >> MongoDB is connecting...
node:internal/modules/cjs/loader:1189
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libuuid.so.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/Discord-Bot/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
Unhandled promise rejection: Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (/home/runner/Discord-Bot/node_modules/discord.js/src/sharding/Shard.js:162:16)
    at Object.onceWrapper (node:events:642:26)
    at Shard.emit (node:events:539:35)
    at Shard._handleExit (/home/runner/Discord-Bot/node_modules/discord.js/src/sharding/Shard.js:412:10)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  code: 'ShardingReadyDied'
}

**Comment by CorwinDev** [comment]
[Please join our Discord](https://discord.gg/qHXxpQKC2H) where we can help you much better
